### ISSUE TITLE
XML parsing crash

### ISSUE THREAD

**Issue by ptr727** [gjbadros/pyvantage#16]
I noticed lots of recent updates to the XML parsing, so I re-tried my config, and it [still](https://github.com/gjbadros/hass-vantage/issues/12) crashes the parser.

Downloaded config file attached.
[192.168.1.3_config.txt](https://github.com/gjbadros/pyvantage/files/11304334/192.168.1.3_config.txt)

**Comment by ptr727** [comment]
Just saw another XML parsing update, still crashes:

```
Exception has occurred: AttributeError
'NoneType' object has no attribute 'text'
  File "C:\Users\piete\source\repos\gjbadros\pyvantage\pyvantage\__init__.py", line 836, in _parse_load_group
    out_name = output_xml.find('DName').text
  File "C:\Users\piete\source\repos\gjbadros\pyvantage\pyvantage\__init__.py", line 501, in parse
    lgroup = self._parse_load_group(lg_xml)
  File "C:\Users\piete\source\repos\gjbadros\pyvantage\pyvantage\__init__.py", line 1402, in do_parse
    parser.parse()
  File "C:\Users\piete\source\repos\gjbadros\pyvantage\pyvantage\__init__.py", line 1397, in load_xml_db
    self.do_parse(xml_db)
  File "C:\Users\piete\source\repos\gjbadros\pyvantage\test.py", line 156, in main
    v.load_xml_db(not args.use_cache)
  File "C:\Users\piete\source\repos\gjbadros\pyvantage\test.py", line 186, in <module>
    main()
AttributeError: 'NoneType' object has no attribute 'text'
```

I've not tried the diff, but maybe have a look at [this](https://github.com/ben-j-h/pyvantage/commit/9cd93c2f5e7c837860ac3ebed89b25704eb21a9b)?

**Comment by gjbadros** [comment]
I'm looking at this today, too -- and incorporating some of that @benj-j-h fix into the master of this repo --thanks!

**Comment by ptr727** [comment]
Tested with the changes, XML load no crashes, thank you.

New verifying correct parsing, based on logs it seems that the group logic is unhappy:

```
        for v in load_vids:
            load = self._vantage._vid_to_load.get(v)
            if not load:
                _LOGGER.warning("LoadGroup %s has unknown load vid %d", self, v)
            if load and load._is_dimmable:
                self._is_dimmable = True
                break
```

```
WARNING:pyvantage:LoadGroup Output name: 'Downstairs-Kitchen-Kitchen Lights' area: 67 type: 'GROUP' load: 'GROUP' id: 501 (ctemp)  ([96, 100, 103, 98, 102]) (c:[]) (b:None) [['1426 3rd Street', 'Downstairs', 'Kitchen', 'Downstairs-Kitchen-Kitchen Lights']] has unknown load vid 96
WARNING:pyvantage:LoadGroup Output name: 'Downstairs-Kitchen-Kitchen Lights' area: 67 type: 'GROUP' load: 'GROUP' id: 501 (ctemp)  ([96, 100, 103, 98, 102]) (c:[]) (b:None) [['1426 3rd Street', 'Downstairs', 'Kitchen', 'Downstairs-Kitchen-Kitchen Lights']] has unknown load vid 100
WARNING:pyvantage:LoadGroup Output name: 'Downstairs-Kitchen-Kitchen Lights' area: 67 type: 'GROUP' load: 'GROUP' id: 501 (ctemp)  ([96, 100, 103, 98, 102]) (c:[]) (b:None) [['1426 3rd Street', 'Downstairs', 'Kitchen', 'Downstairs-Kitchen-Kitchen Lights']] has unknown load vid 103
WARNING:pyvantage:LoadGroup Output name: 'Downstairs-Kitchen-Kitchen Lights' area: 67 type: 'GROUP' load: 'GROUP' id: 501 (ctemp)  ([96, 100, 103, 98, 102]) (c:[]) (b:None) [['1426 3rd Street', 'Downstairs', 'Kitchen', 'Downstairs-Kitchen-Kitchen Lights']] has unknown load vid 98
WARNING:pyvantage:LoadGroup Output name: 'Downstairs-Kitchen-Kitchen Lights' area: 67 type: 'GROUP' load: 'GROUP' id: 501 (ctemp)  ([96, 100, 103, 98, 102]) (c:[]) (b:None) [['1426 3rd Street', 'Downstairs', 'Kitchen', 'Downstairs-Kitchen-Kitchen Lights']] has unknown load vid 102
DEBUG:pyvantage:load group = Output name: 'Downstairs-Kitchen-Kitchen Lights' area: 67 type: 'GROUP' load: 'GROUP' id: 501 (ctemp)  ([96, 100, 103, 98, 102]) (c:[]) (b:None) [['1426 3rd Street', 'Downstairs', 'Kitchen', 'Downstairs-Kitchen-Kitchen Lights']]
```

Investigating the `unknown load`;   
vid 96: `DEBUG:pyvantage:Output = Output name: 'Downstairs-Kitchen-Kitchen Around Island Cans' area: 67 type: 'LIGHT' load: 'Fluor. Electronic non-Dim' vid: 96 @ 0.0  [['1426 3rd Street', 'Downstairs', 'Kitchen', 'Downstairs-Kitchen-Kitchen Around Island Cans']]`
vid 100: `DEBUG:pyvantage:Output = Output name: 'Downstairs-Kitchen-Kitchen Cabinet Strips' area: 67 type: 'LIGHT' load: 'Magnetic Low Voltage' vid: 100 @ 0.0 (dim)  [['1426 3rd Street', 'Downstairs', 'Kitchen', 'Downstairs-Kitchen-Kitchen Cabinet Strips']]`

So the `unknown load` vid's do exist?

**Comment by gjbadros** [comment]
You might need Object//Load (two slashes) around line 463 of __initi__.py
-- a contributed patch changed to a single / looking only for immediate
descendants and I'm not sure that was right and it broke things on
DDGColorLoad for me, and I changed it around line 438 of __init__.py

Can you let me know if that works?

**Comment by ptr727** [comment]
For a quick test I changed all `Object/` to `Object//`, same behavior.

I did some debugging, and `load = self._vantage._vid_to_load.get(v)` and `_vid_to_load` is always empty.

If you have time use the config file I uploaded in the first comment.

**Comment by gjbadros** [comment]
It's actually a new warning that shouldn't really matter, but I do think I
see the problem.  Will fix this week, but I don't think it should impact
using the module significantly (it just means loadgroups won't be dimmable
even if one of the loads in the loadgroup is dimmable).

Is it causing problems?

**Comment by ptr727** [comment]
> Is it causing problems?

Not at the point where I'm testing with HA yet, XML load crashing had always been a blocker :)

The error just did not make sense as the VID does exist but the logic fails to find it.

**Comment by gjbadros** [comment]
Yea, it's fixed now in 0.0.42 -- thanks for the report!

**Comment by ptr727** [comment]
Tested ok, no more not found.

Now looking at `repeated name` warnings:

```
        if obj.name in self._names:
            oldname = obj.name
            obj.name += f" ({obj.vid})"
            if ('0-10V RELAYS' in oldname or
                'NOT USED' in oldname or cmd_type == 'BTN'):
                pass
            else:
                _LOGGER.debug(f"Repeated name `{oldname}' - adding vid to get {obj.name}")
        self._names[obj.name] = obj.vid
```

E.g. for all my SDM12's the sensors have the same name, does the logic rely on names being unique?

Maybe I should just ignore this given the comments in the code `# TODO: this may be a little too hacky` and `# TODO: cleanup this awful logic` :)

**Comment by gjbadros** [comment]
The code automatically adds the vid to differentiate the name if it finds
overlapping names -- this is just a UX issue which you can fix by renaming
the objects with the same name.

**Comment by ptr727** [comment]
Got it, closing as no more crash, thank you, I'll move on to trying HA integration again.

**Comment by gjbadros** [comment]
Make sure you get the latest hass-vantage version that has the stated
dependency on the new release of pyvantage I put up on PyPi
