### ISSUE TITLE
Friendly names get clobbered. Is `Vantage._names` even used?

### ISSUE THREAD

**Issue by loopj** [gjbadros/pyvantage#9]
Hey Greg, thanks for building this, been using it for the past couple of months and it works great.

In Design Center all my Loads have a `Display Name` set up, which I was hoping would just import cleanly into home assistant. 

Unfortunately I noticed this following code clobbers the display names, replacing them with the hierarchical naming, eg. "First Floor-Kitchen-Kitchen Cabinet Lights":
https://github.com/gjbadros/pyvantage/blob/1c8eec3732773784dff356ee937a4b2a07db506d/pyvantage/__init__.py#L993-L996

I understand that the `Vantage.register_id` function is essential for creating the `Vantage._ids` map, but this function also seems to spend a lot of time setting up the `Vantage._names` map too, which as far as I can tell is not used in either pyvantage or hass-vantage. 

I have a few questions - 
- What's the purpose of the `Vantage._names` map?
- Is it intentionally clobbering the Display Name or is this accidental?
- Would you be open to a PR adjusting this logic?

**Comment by filmackay** [comment]
I'd say the philosophy here is that you leave things unnamed, and it gets a sensible hierarchical-based one.

What about putting up a PR that provides the hierarchical name, if there is no display name provided? Otherwise, use the display name - best of both worlds?
